management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  cloudfoundry:
    enabled: true

#axon:
#  distributed:
#    enabled: true
#    spring-cloud:
#      fallback-to-http-get: false

spring:
  datasource:
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect

logging:
  level:
    org:
      springframework:
        web: INFO
    io:
      pivotal: INFO