your:
  host:
   is: "Allard Buijze"

# Set the general logging level within the application
logging:
  level:
    io.pivotal.refarch: DEBUG
    org.hibernate.SQL: INFO

#spring.jpa.generate-ddl: true
#spring.jpa.hibernate:
#  ddl-auto: create-drop
#  naming:
#    physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#spring.jpa.show-sql: true
#spring.jpa.hibernate.use-new-id-generator-mappings: true
#spring.jpa.database-platform: org.hibernate.dialect.MySQL55Dialect

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect

management.endpoint.health.show-details: always